# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'new_ui.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenuBar, QSizePolicy, QStatusBar, QWidget)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 251, 540))
        self.label_18 = QLabel(self.frame)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(15, 15, 60, 25))
        self.Date = QLabel(self.frame)
        self.Date.setObjectName(u"Date")
        self.Date.setGeometry(QRect(75, 12, 160, 31))
        self.label_26 = QLabel(self.frame)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(15, 45, 60, 25))
        self.Time = QLabel(self.frame)
        self.Time.setObjectName(u"Time")
        self.Time.setGeometry(QRect(75, 42, 160, 31))
        self.frame_7 = QFrame(self.frame)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 85, 231, 75))
        self.label_4 = QLabel(self.frame_7)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 8, 211, 20))
        self.Server_Status = QLabel(self.frame_7)
        self.Server_Status.setObjectName(u"Server_Status")
        self.Server_Status.setGeometry(QRect(10, 32, 211, 35))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(15, 175, 220, 25))
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(15, 205, 220, 20))
        self.Driver_Name = QLabel(self.frame)
        self.Driver_Name.setObjectName(u"Driver_Name")
        self.Driver_Name.setGeometry(QRect(25, 225, 210, 31))
        self.line_4 = QFrame(self.frame)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(10, 265, 231, 2))
        self.label_19 = QLabel(self.frame)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(15, 280, 220, 20))
        self.Driver_ID = QLabel(self.frame)
        self.Driver_ID.setObjectName(u"Driver_ID")
        self.Driver_ID.setGeometry(QRect(25, 300, 210, 31))
        self.line_5 = QFrame(self.frame)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 340, 231, 2))
        self.label_25 = QLabel(self.frame)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(15, 355, 220, 20))
        self.Vehicle_ID = QLabel(self.frame)
        self.Vehicle_ID.setObjectName(u"Vehicle_ID")
        self.Vehicle_ID.setGeometry(QRect(25, 375, 210, 31))
        self.line_6 = QFrame(self.frame)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(10, 520, 231, 2))
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(275, 10, 411, 161))
        self.label_8 = QLabel(self.frame_3)
        self.label_8.setObjectName(u"label_8;")
        self.label_8.setGeometry(QRect(10, 15, 391, 35))
        self.Speed = QLabel(self.frame_3)
        self.Speed.setObjectName(u"Speed")
        self.Speed.setGeometry(QRect(10, 55, 391, 91))
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(275, 185, 411, 231))
        self.Main_status = QLabel(self.frame_2)
        self.Main_status.setObjectName(u"Main_status")
        self.Main_status.setGeometry(QRect(10, 15, 391, 41))
        self.Val_1 = QLabel(self.frame_2)
        self.Val_1.setObjectName(u"Val_1")
        self.Val_1.setGeometry(QRect(10, 65, 391, 81))
        self.Sub_status = QLabel(self.frame_2)
        self.Sub_status.setObjectName(u"Sub_status")
        self.Sub_status.setGeometry(QRect(40, 175, 160, 31))
        self.Val_2 = QLabel(self.frame_2)
        self.Val_2.setObjectName(u"Val_2")
        self.Val_2.setGeometry(QRect(210, 175, 160, 31))
        self.frame_5 = QFrame(self.centralwidget)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(275, 430, 411, 120))
        self.label_2 = QLabel(self.frame_5)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(15, 12, 181, 25))
        self.GPS_Status = QLabel(self.frame_5)
        self.GPS_Status.setObjectName(u"GPS_Status")
        self.GPS_Status.setGeometry(QRect(220, 12, 175, 25))
        self.label_7 = QLabel(self.frame_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(15, 50, 90, 25))
        self.Latitude = QLabel(self.frame_5)
        self.Latitude.setObjectName(u"Latitude")
        self.Latitude.setGeometry(QRect(110, 50, 280, 25))
        self.label_6 = QLabel(self.frame_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(15, 80, 90, 25))
        self.Longtitude = QLabel(self.frame_5)
        self.Longtitude.setObjectName(u"Longtitude")
        self.Longtitude.setGeometry(QRect(110, 80, 280, 25))
        self.frame_4 = QFrame(self.centralwidget)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(700, 10, 311, 540))
        self.Status_frame = QFrame(self.frame_4)
        self.Status_frame.setObjectName(u"Status_frame")
        self.Status_frame.setGeometry(QRect(10, 10, 291, 140))
        self.label_30 = QLabel(self.Status_frame)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 15, 271, 31))
        self.Driving_Status = QLabel(self.Status_frame)
        self.Driving_Status.setObjectName(u"Driving_Status")
        self.Driving_Status.setGeometry(QRect(10, 55, 271, 61))
        self.label_13 = QLabel(self.frame_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 165, 80, 20))
        self.label_16 = QLabel(self.frame_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(140, 165, 150, 20))
        self.Driv_R1 = QLabel(self.frame_4)
        self.Driv_R1.setObjectName(u"Driv_R1")
        self.Driv_R1.setGeometry(QRect(20, 185, 120, 31))
        self.Drive_R1_Val = QLabel(self.frame_4)
        self.Drive_R1_Val.setObjectName(u"Drive_R1_Val")
        self.Drive_R1_Val.setGeometry(QRect(140, 185, 150, 31))
        self.line_2 = QFrame(self.frame_4)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(15, 225, 281, 2))
        self.label_14 = QLabel(self.frame_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 235, 80, 20))
        self.label_17 = QLabel(self.frame_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(140, 235, 150, 20))
        self.Drive_R2 = QLabel(self.frame_4)
        self.Drive_R2.setObjectName(u"Drive_R2")
        self.Drive_R2.setGeometry(QRect(20, 255, 120, 31))
        self.Drive_R2_val = QLabel(self.frame_4)
        self.Drive_R2_val.setObjectName(u"Drive_R2_val")
        self.Drive_R2_val.setGeometry(QRect(140, 255, 150, 31))
        self.line = QFrame(self.frame_4)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(15, 295, 281, 2))
        self.label_15 = QLabel(self.frame_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 305, 80, 20))
        self.label_20 = QLabel(self.frame_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(140, 305, 150, 20))
        self.Drive_R3 = QLabel(self.frame_4)
        self.Drive_R3.setObjectName(u"Drive_R3")
        self.Drive_R3.setGeometry(QRect(20, 325, 120, 31))
        self.Drive_R3_Val = QLabel(self.frame_4)
        self.Drive_R3_Val.setObjectName(u"Drive_R3_Val")
        self.Drive_R3_Val.setGeometry(QRect(140, 325, 150, 31))
        self.line_3 = QFrame(self.frame_4)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(15, 365, 281, 2))
        self.label_21 = QLabel(self.frame_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 385, 140, 31))
        self.Drive_total = QLabel(self.frame_4)
        self.Drive_total.setObjectName(u"Drive_total")
        self.Drive_total.setGeometry(QRect(160, 385, 131, 31))
        self.label_23 = QLabel(self.frame_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 425, 271, 20))
        self.Rest_Next = QLabel(self.frame_4)
        self.Rest_Next.setObjectName(u"Rest_Next")
        self.Rest_Next.setGeometry(QRect(20, 450, 271, 41))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Driver Telematics Dashboard", None))
        MainWindow.setStyleSheet(QCoreApplication.translate("MainWindow", u"QMainWindow { background-color: #121824; }\n"
"QFrame { background-color: #1e293b; border-radius: 12px; border: none; }\n"
"QLabel { color: #e2e8f0; font-family: 'Segoe UI', 'Kanit'; }\n"
"QFrame[frameShape=\"4\"] { background-color: #334155; max-height: 2px; }", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Date :", None))
        self.label_18.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 13pt; color: #94a3b8;", None))
        self.Date.setText(QCoreApplication.translate("MainWindow", u"00/00/0000", None))
        self.Date.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 16pt; font-weight: bold; color: #38bdf8;", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Time :", None))
        self.label_26.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 13pt; color: #94a3b8;", None))
        self.Time.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.Time.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 16pt; font-weight: bold; color: #38bdf8;", None))
        self.frame_7.setStyleSheet(QCoreApplication.translate("MainWindow", u"background-color: #0f172a; border: 1px solid #334155;", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"SERVER STATUS", None))
        self.label_4.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 10pt; color: #64748b; font-weight: bold;", None))
        self.Server_Status.setText(QCoreApplication.translate("MainWindow", u"connected", None))
        self.Server_Status.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 18pt; font-weight: bold; color: #4ade80;", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e1e\u0e19\u0e31\u0e01\u0e07\u0e32\u0e19\u0e02\u0e31\u0e1a\u0e23\u0e16", None))
        self.label.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 13pt; font-weight: bold; color: #f1f5f9;", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_11.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 10pt; color: #64748b;", None))
        self.Driver_Name.setText(QCoreApplication.translate("MainWindow", u"mr. michel dean", None))
        self.Driver_Name.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 15pt; font-weight: 600;", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Driver ID", None))
        self.label_19.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 10pt; color: #64748b;", None))
        self.Driver_ID.setText(QCoreApplication.translate("MainWindow", u"123456789", None))
        self.Driver_ID.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 15pt; font-weight: 600;", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Vehicle ID", None))
        self.label_25.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 10pt; color: #64748b;", None))
        self.Vehicle_ID.setText(QCoreApplication.translate("MainWindow", u"123456789", None))
        self.Vehicle_ID.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 15pt; font-weight: 600;", None))
        self.frame_3.setStyleSheet(QCoreApplication.translate("MainWindow", u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1e293b, stop:1 #0f172a); border: 1px solid #334155;", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Speed (km/h)", None))
        self.label_8.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 16pt; font-weight: bold; color: #94a3b8;", None))
        self.Speed.setText(QCoreApplication.translate("MainWindow", u"   xx", None))
        self.Speed.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 55pt; font-weight: bold; color: #f59e0b;", None))
        self.Main_status.setText(QCoreApplication.translate("MainWindow", u"xxx", None))
        self.Main_status.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 22pt; font-weight: bold; color: #38bdf8; qproperty-alignment: 'AlignHCenter | AlignVCenter';", None))
        self.Val_1.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.Val_1.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 45pt; font-weight: bold;", None))
        self.Sub_status.setText(QCoreApplication.translate("MainWindow", u"xxx", None))
        self.Sub_status.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 13pt; color: #94a3b8;", None))
        self.Val_2.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.Val_2.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 15pt; font-weight: 600; color: #cbd5e1;", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07 GPS", None))
        self.label_2.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 12pt; font-weight: bold;", None))
        self.GPS_Status.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e16\u0e32\u0e19\u0e30 GPS", None))
        self.GPS_Status.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 11pt; font-weight: bold; color: #4ade80;", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Latitude", None))
        self.label_7.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 11pt; color: #94a3b8;", None))
        self.Latitude.setText(QCoreApplication.translate("MainWindow", u"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07 Lat", None))
        self.Latitude.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 13pt; font-weight: 600;", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"longitude", None))
        self.label_6.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 11pt; color: #94a3b8;", None))
        self.Longtitude.setText(QCoreApplication.translate("MainWindow", u"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07 Lat", None))
        self.Longtitude.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 13pt; font-weight: 600;", None))
        self.Status_frame.setStyleSheet(QCoreApplication.translate("MainWindow", u"background-color: #0f172a; border: 1px solid #334155;", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Driving Status", None))
        self.label_30.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 13pt; color: #64748b; font-weight: bold;", None))
        self.Driving_Status.setText(QCoreApplication.translate("MainWindow", u"Driving", None))
        self.Driving_Status.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 26pt; font-weight: bold; color: #ef4444;", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"ROUND 1", None))
        self.label_13.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 10pt; font-weight: bold; color: #38bdf8;", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e16\u0e32\u0e19\u0e30\u0e01\u0e32\u0e23\u0e17\u0e33\u0e07\u0e32\u0e19", None))
        self.label_16.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 10pt; color: #94a3b8;", None))
        self.Driv_R1.setText(QCoreApplication.translate("MainWindow", u"Driving time :", None))
        self.Driv_R1.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 12pt; color: #cbd5e1;", None))
        self.Drive_R1_Val.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.Drive_R1_Val.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 15pt; font-weight: bold;", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"ROUND 2", None))
        self.label_14.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 10pt; font-weight: bold; color: #38bdf8;", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e16\u0e32\u0e19\u0e30\u0e01\u0e32\u0e23\u0e17\u0e33\u0e07\u0e32\u0e19", None))
        self.label_17.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 10pt; color: #94a3b8;", None))
        self.Drive_R2.setText(QCoreApplication.translate("MainWindow", u"Driving time :", None))
        self.Drive_R2.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 12pt; color: #cbd5e1;", None))
        self.Drive_R2_val.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.Drive_R2_val.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 15pt; font-weight: bold;", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"ROUND 3", None))
        self.label_15.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 10pt; font-weight: bold; color: #38bdf8;", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e16\u0e32\u0e19\u0e30\u0e01\u0e32\u0e23\u0e17\u0e33\u0e07\u0e32\u0e19", None))
        self.label_20.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 10pt; color: #94a3b8;", None))
        self.Drive_R3.setText(QCoreApplication.translate("MainWindow", u"Driving time :", None))
        self.Drive_R3.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 12pt; color: #cbd5e1;", None))
        self.Drive_R3_Val.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.Drive_R3_Val.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 15pt; font-weight: bold;", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Driving time total :", None))
        self.label_21.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 12pt; font-weight: 500; color: #94a3b8;", None))
        self.Drive_total.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.Drive_total.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 16pt; font-weight: bold; color: #22c55e;", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Camera :", None))
        self.label_23.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 11pt; color: #94a3b8;", None))
        self.Rest_Next.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.Rest_Next.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 22pt; font-weight: bold; color: #a855f7;", None))
        self.label_8.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 11pt; color: #94a3b8;qproperty-alignment: 'AlignHCenter | AlignVCenter';", None))
        self.label_30.setStyleSheet(QCoreApplication.translate("MainWindow", u"font-size: 11pt; color: #94a3b8;qproperty-alignment: 'AlignHCenter | AlignVCenter';", None))

